Add code from bad repo without template
HaMeCTHuK/explore-with-me pull request #1
Opened 2024-07-04 12:49 UTC by HaMeCTHuK

Add code from bad repo. Test

2024-07-05 07:44 UTC, LexLippi requested changes
Привет!

Отличная работа!

Есть пара мелких замечаний, которые необходимо исправить!

Желаю удачи!

2024-07-05 07:44 UTC, LexLippi commented on stats-server/stat-service/src/main/java/ru/practicum/server/controller/StatController.java
> +                                       @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime end,
формат времени можно в константу проекта вынести, так как он скорее всего будет единым для всех частей

2024-07-05 07:44 UTC, LexLippi commented on stats-server/stat-service/src/main/java/ru/practicum/server/mapper/StatMapper.java
> +public class StatMapper {
`@UtilityClass` забыл

2024-07-05 07:44 UTC, LexLippi commented on stats-server/stat-service/src/main/java/ru/practicum/server/service/StatServiceImpl.java
> +                : statRepository.findStat(start, end, uris);
Для такого сложного условия лучше не использовать тернарный оператор, иначе он становится не читаемым

2024-07-05 07:44 UTC, LexLippi commented on stats-server/stat-service/src/main/resources/schema.sql
> +    uri VARCHAR(2083),
может быть `null`?

2024-07-05 20:05 UTC, HaMeCTHuK commented on stats-server/stat-service/src/main/java/ru/practicum/server/mapper/StatMapper.java
> +public class StatMapper {
Поправил

2024-07-05 20:06 UTC, HaMeCTHuK commented on stats-server/stat-service/src/main/java/ru/practicum/server/service/StatServiceImpl.java
> +                : statRepository.findStat(start, end, uris);
Понял, поправил

2024-07-05 20:06 UTC, HaMeCTHuK commented on stats-server/stat-service/src/main/resources/schema.sql
> +    uri VARCHAR(2083),
Убрал)))

2024-07-05 20:09 UTC, HaMeCTHuK commented on stats-server/stat-service/src/main/java/ru/practicum/server/controller/StatController.java
> +                                       @RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime end,
Понял, спасибо. Вынес в отдельную ветку.

2024-07-06 08:24 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи со следующими частями диплома!

2024-07-08 07:56 UTC, merged