Main svc
HaMeCTHuK/explore-with-me pull request #2
Opened 2024-07-09 11:27 UTC by HaMeCTHuK

TEST

2024-07-10 09:13 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть некоторое количество замечаний, которые необходмо исправить!

Желаю удачи!

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/category/controller/CategoryPublicController.java
> +    public Collection<CategoryDto> getAllCategories(@RequestParam(value = "from", required = false, defaultValue = "0")
В `required = false` нет необходимости, так как оно автоматически устанавливается таким при использовании `defaultValue`

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/category/controller/CategoryPublicController.java
> +                                                    final Integer from,
Тут видимо правильнее неотрицательным :)

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/category/controller/CategoryPublicController.java
> +                                                    @RequestParam(value = "size", required = false, defaultValue = "10")
`required = false` не нужно

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        } else {
`else` не нужен, так как ты делаешь `return` в основной ветке условного оператора

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        if (categories.isEmpty()) {
В условном операторе нет смысла, так как преобразование, которое ты сделаешь с помощью Stream API аналогично вернет пустой список

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        } else {
`else` не нужен

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/compilation/controller/CompilationPublicController.java
> +                                                         @RequestParam(value = "from", required = false, defaultValue = "0")
`required = false` не нужен

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/compilation/controller/CompilationPublicController.java
> +                                                         @RequestParam(value = "size", required = false, defaultValue = "10")
`required = false` не нужен

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/event/controller/EventAdminController.java
> +                                             @Positive(message = "Значение 'size' должно быть положительным") Integer size) {
`required = false` не нужен

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/event/controller/EventAdminController.java
> +                                             @RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Строку с форматом времени лучше вынести в константу

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/user/controller/UserAdminController.java
> +                                           @Positive(message = "Значение 'size' должно быть положительным")
`required = false` не нужен

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/event/controller/EventPublicController.java
> +                                             @Positive @RequestParam(defaultValue = "10") int size,
`required = false` в случаях, где есть `defaultValue`  не нужен

2024-07-10 09:13 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/event/controller/EventPrivateController.java
> +                                                   final Integer size) {
`required = false` не нужен

2024-07-10 09:28 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/category/controller/CategoryPublicController.java
> +    public Collection<CategoryDto> getAllCategories(@RequestParam(value = "from", required = false, defaultValue = "0")
Исправил

2024-07-10 09:32 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/category/controller/CategoryPublicController.java
> +                                                    final Integer from,
Точно!! Поправил)))

2024-07-10 09:34 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/category/controller/CategoryPublicController.java
> +                                                    @RequestParam(value = "size", required = false, defaultValue = "10")
Исправил.

2024-07-10 09:37 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        if (categories.isEmpty()) {
Понял. Спасибо. Стримы надо еще подтянуть

2024-07-10 09:38 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        } else {
Поправил

2024-07-10 09:39 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/compilation/controller/CompilationPublicController.java
> +                                                         @RequestParam(value = "from", required = false, defaultValue = "0")
ПОправил

2024-07-10 09:40 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/compilation/controller/CompilationPublicController.java
> +                                                         @RequestParam(value = "size", required = false, defaultValue = "10")
Попрравил

2024-07-10 09:41 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/event/controller/EventAdminController.java
> +                                             @Positive(message = "Значение 'size' должно быть положительным") Integer size) {
Поправил

2024-07-10 09:44 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/event/controller/EventAdminController.java
> +                                             @RequestParam(required = false) @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
Так и думал что где то пропустил.... Поправил

2024-07-10 09:45 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +        } else {
Убрал

2024-07-10 09:46 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/user/controller/UserAdminController.java
> +                                           @Positive(message = "Значение 'size' должно быть положительным")
Поправил

2024-07-10 09:48 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/event/controller/EventPublicController.java
> +                                             @Positive @RequestParam(defaultValue = "10") int size,
Поправил

2024-07-10 09:49 UTC, HaMeCTHuK commented on ewm-service/src/main/java/ru/practicum/event/controller/EventPrivateController.java
> +                                                   final Integer size) {
Поправил

2024-07-11 13:29 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи с заключительным этапом диплома!

2024-07-14 11:30 UTC, merged